version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: "goshop-postgresdb"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=goshop
    ports:
      - "5432:5432"